name: 'CI environment setup'
description: 'Shared config for all workflows setup'

inputs:
  coverage_report_path:
    description: "Phpunit coverage report file path. If empty - code coverage will not be executed."
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'


    - name: When has report path
      if: ${{ inputs.coverage_report_path != '' }}
      shell: bash
      run: |
        touch HAS_report_path.txt
        ls -la .

    - name: When has no report path
      if: ${{ inputs.coverage_report_path == '' }}
      shell: bash
      run: |
        touch NO_report_path.txt
        ls -la .

#    - name: get dir name
#      id: dir_name
#      shell: bash
#      run: |
#        echo "mkdir_name=dir1111" >> $GITHUB_OUTPUT
#
#    - name: create dir
#      shell: bash
#      run: |
#        mkdir ${{steps.dir_name.outputs.mkdir_name}}
#
#
#    - name: LS
#      shell: bash
#      run: |
#        ls -lah .