name: 'CI environment setup'
description: 'Shared config for all workflows setup'


runs:
  using: "composite"
  steps:
    - name: Setup environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: get dir name
      id: dir_name
      shell: bash
      run: |
        echo "mkdir_name=dir1111" >> $GITHUB_OUTPUT

    - name: create dir
      shell: bash
      run: |
        mkdir ${{steps.dir_name.outputs.mkdir_name}}


    - name: LS
      shell: bash
      run: |
        ls -lah .