name: PHP Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer:3.4.0

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: repo


      - name: Install dependencies
        run: |
          cd repo
          composer install

      - name: Unit tests and code coverage report
        run: |
          cd repo
          composer run-script test:coverage
          head -n9 coverage/cover.txt | tail -n3 > coverage/coverageSummary.txt

      - name: Leave PR summary
        uses: LazyNewbie/gh_action_test@master
        with:
          report-file: repo/coverage/coverageSummary.txt


