name: PHP Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer:3.4.0

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: repo


      - name: Install dependencies
        run: |
          cd repo
          composer install

      #      - name: "Upload coverage data"
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: covdata
      #          path: gh_output/clover.xml


      - name: Run test suite
        run: |
          cd repo
          composer run-script test:coverage

      - name: PHPUnit Coverage Check
        uses: ericsizemore/phpunit-coverage-check-action@1.0.1
        with:
          clover_file: 'repo/coverage/clover.xml'
          threshold: 10

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: 'repo/coverage/clover.xml'
          coverage_badge_path: ./output/coverage.svg
          push_badge: false

      - name: GitHub Pages v4
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #       deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./output
          publish_branch: bages-data
          commit_message: ${{ github.event.head_commit.message }}

      - name: Leave PR summary
        uses: actions/github-script@v6
        with:
          script: |
            let summaries = github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            console.info(summaries);
            summaries.forEach((item)=>{
              console.log(item);
            })
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! <img src="https://raw.githubusercontent.com/LazyNewbie/gh_test/bages-data/coverage.svg?token=GHSAT0AAAAAACSKF3SV44NSCO477CUPHXS6ZV3EPBA">'
            })
