name: PHP Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer:3.4.0

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: repo


      - name: Install dependencies
        run: |
          cd repo
          composer install

      #      - name: "Upload coverage data"
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: covdata
      #          path: gh_output/clover.xml


      - name: Run test suite
        run: |
          cd repo
          composer run-script test:coverage

      - name: PHPUnit Coverage Check
        uses: ericsizemore/phpunit-coverage-check-action@1.0.1
        with:
          clover_file: 'repo/coverage/clover.xml'
          threshold: 70

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: 'repo/coverage/clover.xml'
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: LS -LA output
        run: |
          ls -la repo/output

      - name: LS -LA ./output
        run: |
          ls -la ./output

      - name: GitHub Pages v3
        uses: peaceiris/actions-github-pages@v3.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: repo/output
          publish_branch: bages-data
