name: EXADS Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer:3.4.0

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Install dependencies
        run: |
          cd repo
          composer install

      #      - name: "Upload coverage data"
      #        uses: actions/upload-artifact@v3
      #        with:
      #          name: covdata
      #          path: gh_output/clover.xml


      - name: Run test suite
        run: |
          cd repo
          composer run-script test:coverage
          ls -la .

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          report: ${{ GITHUB_WORKSPACE }}/coverage/clover.xml
          coverage_badge_path: output/coverage.svg
          push_badge: false

      - name: Git push to image-data branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'alexey@exads.com'