name: EXADS Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: php-cs-fixer:3.4.0
          extensions: memcached

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: repo

      - name: Composer update
        uses: php-actions/composer@v5
        with:
          command: update
          args: --with-all-dependencies --optimize-autoloader --prefer-dist --ignore-platform-reqs --working-dir=repo

      - name: Run test suite
        run: |
          cd repo
          composer run-script test
